{% set run_hr = task_instance.xcom_pull(task_ids = "get_run_hr") %}

CREATE TABLE IF NOT EXISTS sandbox_data_pipeline.cocktails
(
    date_modified               TIMESTAMP,
    id_drink                    NUMERIC,
    alcoholic                   STRING,
    category                    STRING,
    creative_commons_confirmed  STRING,
    drink                       STRING,
    drink_alternate             STRING,
    drink_thumb                 STRING,
    glass                       STRING,
    iba                         STRING,
    image_attribution           STRING,
    image_source                STRING,
    ingredient1                 STRING,
    ingredient10                STRING,
    ingredient11                STRING,
    ingredient12                STRING,
    ingredient13                STRING,
    ingredient14                STRING,
    ingredient15                STRING,
    ingredient2                 STRING,
    ingredient3                 STRING,
    ingredient4                 STRING,
    ingredient5                 STRING,
    ingredient6                 STRING,
    ingredient7                 STRING,
    ingredient8                 STRING,
    ingredient9                 STRING,
    instructions                STRING,
    instructions_de             STRING,
    instructions_es             STRING,
    instructions_fr             STRING,
    instructions_it             STRING,
    instructions_zh_hans        STRING,
    instructions_zh_hant        STRING,
    measure1                    STRING,
    measure10                   STRING,
    measure11                   STRING,
    measure12                   STRING,
    measure13                   STRING,
    measure14                   STRING,
    measure15                   STRING,
    measure2                    STRING,
    measure3                    STRING,
    measure4                    STRING,
    measure5                    STRING,
    measure6                    STRING,
    measure7                    STRING,
    measure8                    STRING,
    measure9                    STRING,
    tags                        STRING,
    video                       STRING,
    run_hr                      INTEGER NOT NULL,
    created_at_ts               TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);




delete
from sandbox_data_pipeline.cocktails
where run_hr = {{ run_hr }};

insert into sandbox_data_pipeline.cocktails
(
          date_modified,
          id_drink,
          alcoholic,
          category,
          creative_commons_confirmed,
          drink,
          drink_alternate,
          drink_thumb,
          glass,
          iba,
          image_attribution,
          image_source,
          ingredient1,
          ingredient10,
          ingredient11,
          ingredient12,
          ingredient13,
          ingredient14,
          ingredient15,
          ingredient2,
          ingredient3,
          ingredient4,
          ingredient5,
          ingredient6,
          ingredient7,
          ingredient8,
          ingredient9,
          instructions,
          instructions_de,
          instructions_es,
          instructions_fr,
          instructions_it,
          `instructions_zh_hans`,
          `instructions_zh_hant`,
          measure1,
          measure10,
          measure11,
          measure12,
          measure13,
          measure14,
          measure15,
          measure2,
          measure3,
          measure4,
          measure5,
          measure6,
          measure7,
          measure8,
          measure9,
          tags,
          video,
          run_hr
)
SELECT
         drink.dateModified,
         drink.idDrink,
         drink.strAlcoholic,
         drink.strCategory,
         drink.strCreativeCommonsConfirmed,
         drink.strDrink,
         drink.strDrinkAlternate,
         drink.strDrinkThumb,
         drink.strGlass,
         drink.strIBA,
         drink.strImageAttribution,
         drink.strImageSource,
         drink.strIngredient1,
         drink.strIngredient10,
         drink.strIngredient11,
         drink.strIngredient12,
         drink.strIngredient13,
         drink.strIngredient14,
         drink.strIngredient15,
         drink.strIngredient2,
         drink.strIngredient3,
         drink.strIngredient4,
         drink.strIngredient5,
         drink.strIngredient6,
         drink.strIngredient7,
         drink.strIngredient8,
         drink.strIngredient9,
         drink.strInstructions,
         drink.strInstructionsDE,
         drink.strInstructionsES,
         drink.strInstructionsFR,
         drink.strInstructionsIT,
         drink.`strInstructionsZH-HANS`,
         drink.`strInstructionsZH-HANT`,
         drink.strMeasure1,
         drink.strMeasure10,
         drink.strMeasure11,
         drink.strMeasure12,
         drink.strMeasure13,
         drink.strMeasure14,
         drink.strMeasure15,
         drink.strMeasure2,
         drink.strMeasure3,
         drink.strMeasure4,
         drink.strMeasure5,
         drink.strMeasure6,
         drink.strMeasure7,
         drink.strMeasure8,
         drink.strMeasure9,
         drink.strTags,
         drink.strVideo,
        {{ run_hr }}
from sandbox_data_pipeline.cocktails_stage c
cross join unnest(c.drinks) as drink;
